name: Deploy LLM Stack

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run deployment script
        run: |
          chmod +x deploy_llm_stack.sh
          ./deploy_llm_stack.sh
